---
- hosts: aws_fkemedicure_k8s_master
  become: yes
  tasks:
    - name: Update apt cache
      shell: apt update

    - name: Install Docker
      shell: |
        apt install -y docker.io
        systemctl enable docker
        systemctl start docker

    - name: Add Kubernetes apt-key and repository
      shell: |
        timeout 30s curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
        timeout 60s apt update
      args:
        warn: false

    - name: Install Kubernetes components (kubeadm, kubelet, kubectl)
      shell: |
        apt install -y kubeadm kubelet kubectl

    - name: Initialize Kubernetes master
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_init_output

    - name: Configure kubectl for Jenkins user
      shell: |
        mkdir -p /home/ubuntu/.kube
        cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
        chown ubuntu:ubuntu /home/ubuntu/.kube/config

    - name: Set up Flannel network
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: Save join command to file for worker nodes
      shell: |
        kubeadm token create --print-join-command > /home/ubuntu/kube_join_command.sh
      args:
        creates: /home/ubuntu/kube_join_command.sh
      register: join_command_output

- hosts:
    - aws_fkemedicure_k8s_worker01
    - aws_fkemedicure_k8s_worker02
  become: yes
  tasks:
    - name: Update apt cache
      shell: apt update

    - name: Install Docker
      shell: |
        apt install -y docker.io
        systemctl enable docker
        systemctl start docker

    - name: Add Kubernetes apt-key and repository
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
        apt update

    - name: Install Kubernetes components (kubeadm, kubelet, kubectl)
      shell: |
        apt install -y kubeadm kubelet kubectl
    - name: Copy join command script from master to worker
      copy:
        src: /home/ubuntu/kube_join_command.sh
        dest: /home/ubuntu/kube_join_command.sh
        mode: '0755'

    - name: Join the Kubernetes cluster
      shell: |
        $(cat /home/ubuntu/kube_join_command.sh)
