---
- hosts: aws_fkemedicure_k8s_master
  become: yes
  tasks:
    - name: Update apt and install Docker
      shell: |
        sudo apt update && \
        sudo apt install docker.io -y && \
        sudo systemctl enable docker && \
        sudo systemctl start docker

    - name: Add Kubernetes apt repository key
      shell: |
        sudo mkdir -p /etc/apt/keyrings && \
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes apt repository
      shell: |
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

    - name: Update apt cache and install Kubernetes components
      shell: |
        sudo apt update && \
        sudo apt install -y kubeadm kubelet kubectl

    - name: Enable and start kubelet service
      shell: |
        sudo systemctl enable kubelet && \
        sudo systemctl start kubelet
