---
- hosts:
    - aws_fkemedicure_k8s_worker01
    - aws_fkemedicure_k8s_worker02
  become: yes
  tasks:
    - name: Update apt cache
      shell: apt update

    - name: Install Docker
      shell: |
        apt install -y docker.io
        systemctl enable docker
        systemctl start docker

    - name: Add Kubernetes apt-key and repository
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
        apt update

    - name: Install Kubernetes components (kubeadm, kubelet, kubectl)
      shell: |
        apt install -y kubeadm kubelet kubectl

    - name: Join the Kubernetes cluster
      shell: |
        $(cat /home/ubuntu/kube_join_command.sh)
