---
- hosts: aws_fkemedicure_k8s_master
  become: yes
  tasks:
    - name: Update apt cache
      shell: apt update
      become: yes

    - name: Install Docker
      shell: |
        apt install -y docker.io
        systemctl enable docker
        systemctl start docker
      become: yes

    - name: Add Kubernetes apt-key and repository
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
        apt update
      become: yes

    - name: Install Kubernetes components (kubeadm, kubelet, kubectl)
      shell: |
        apt install -y kubeadm kubelet kubectl
      become: yes

    - name: Initialize Kubernetes master
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_init_output

    - name: Configure kubectl for Jenkins user
      shell: |
        mkdir -p /home/ubuntu/.kube
        cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
        chown ubuntu:ubuntu /home/ubuntu/.kube/config
      become: yes

    - name: Set up Flannel network
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
      become: yes

    - name: Save join command to file for worker nodes
      shell: |
        kubeadm token create --print-join-command > /home/ubuntu/kube_join_command.sh
      args:
        creates: /home/ubuntu/kube_join_command.sh
      become: yes
      register: join_command_output

- hosts: aws_fkemedicure_k8s_worker
  become: yes
  tasks:
    - name: Update apt cache
      shell: apt update
      become: yes

    - name: Install Docker
      shell: |
        apt install -y docker.io
        systemctl enable docker
        systemctl start docker
      become: yes

    - name: Add Kubernetes apt-key and repository
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
        apt update
      become: yes

    - name: Install Kubernetes components (kubeadm, kubelet, kubectl)
      shell: |
        apt install -y kubeadm kubelet kubectl
      become: yes

    - name: Join the Kubernetes cluster
      shell: |
        $(cat /home/ubuntu/kube_join_command.sh)
      become: yes
