---
- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  tasks: 
    - name: Update apt package index
      yum:
        update_cache: yes

    - name: Install Docker
      yum:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Deploy Docker container
      docker_container:
        name: fkemedicure
        image: fahamie/fkemedicure
        state: started
        restart_policy: always
        published_ports:
          - "8084:8081"
