plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  "tag:Name": fkemedicure
  instance-state-name: running
strict: False
keyed_groups:
  - key: tags.Name
    prefix: aws
ansible_user: ec2-user
ansible_ssh_private_key_file: /var/lib/jenkins/ansible_key.pem
